### ISSUE TITLE
Could the output class name be changed ?

### ISSUE THREAD

**Issue by zangbianxuegu** [ericam/compass-animate#18]
The Template:
// @include animate[-animationName]([$sub: all, $class: false]);

If I use @include animate-flash($class:true);  the output class name was .flash.

Could it be changed ?

**Comment by jorge-d** [comment]
Hi,

Doing `@include animate-flash($class:true);` will just create a css helper:
```css
.animationName {
  -webkit-animation-name: animationName;
  -moz-animation-name: animationName;
  -o-animation-name: animationName;
  animation-name: animationName;
}
```

What you can do is create your own helper:
```scss
.yourCustomClassName {
    @include animation(animationName 0.8s linear forwards);
  }
```
